services:
  - type: web
    name: bot-geralt
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: MODERATOR_ROLE_ID
        sync: false
      - key: STAFF_ROLE_ID
        sync: false
      - key: WEBHOOK_PORT
        value: 10000
